<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search courses_search</name>
   <tag></tag>
   <elementGuidId>47dfe717-1725-4deb-8a28-7b3122e62dcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coursesearchbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coursesearchbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#coursesearchbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6876ea30-ac24-4826-ac51-55599a8213cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coursesearchbox</value>
      <webElementGuid>679f7db0-2356-4ee3-8ef6-73e41db72698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d73e8116-b692-409c-b3ec-00a71bf2623e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>if(this.value =='Search courses' ) this.value=''</value>
      <webElementGuid>d1ca061a-86b0-4de0-8965-8a7e92e16048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>if(this.value=='') this.value='Search courses'</value>
      <webElementGuid>3efa60d0-102e-49db-8b84-260ee321f629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search courses</value>
      <webElementGuid>ccfaffef-a707-4c80-8e84-734a434d56df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>6609a54a-0c6d-4311-9ad4-170c0e5d65a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coursesearchbox&quot;)</value>
      <webElementGuid>05924fc6-c653-483b-a95e-fb42bbd14bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coursesearchbox']</value>
      <webElementGuid>59d90bee-3c46-4ce2-9323-fa3e6c4a6bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search']/input</value>
      <webElementGuid>dc3c44c8-9cf5-405d-acd2-1b306500aa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>da7ea120-e39e-41bc-bc80-1521c7d76025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'coursesearchbox' and @type = 'text' and @name = 'search']</value>
      <webElementGuid>7eb8cba8-b8f5-4aa1-8100-972993d2e43a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
